# Generated by Django 4.2.7 on 2025-08-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_dashboard', '0002_activitylog_user_alter_activitylog_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottask',
            name='average_creation_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bottask',
            name='current_proxy_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bottask',
            name='last_rate_limit_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bottask',
            name='rate_limit_hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bottask',
            name='success_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
