# Generated by Django 4.2.7 on 2025-07-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emulatorprofile',
            name='screen_resolution',
        ),
        migrations.AddField(
            model_name='device',
            name='connection_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='device',
            name='connection_type',
            field=models.CharField(choices=[('usb', 'USB'), ('wifi', 'WiFi'), ('bluetooth', 'Bluetooth')], default='usb', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='is_emulator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emulatorprofile',
            name='api_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emulatorprofile',
            name='device_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='emulatorprofile',
            name='ios_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='emulatorprofile',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emulatorprofile',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=20),
        ),
        migrations.AddField(
            model_name='emulatorprofile',
            name='resolution',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emulatorprofile',
            name='android_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emulatorprofile',
            name='emulator_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='emulatorprofile',
            name='ram_size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
